### ISSUE TITLE
G.Skill Trident Z RGB modules not working with 400 kHz I2C frequency

### ISSUE THREAD

**Issue by daskanu** [1a2m3/SPD-Reader-Writer#1]
Hello 1a2m3,

first of all let me say thank you for this great project.

I found that the EEPROM of my G.Skill Trident Z RGB modules is not detected as long as the I2C freqeny is set to 400 kHz.
When commenting out the following line in the setup() method everything is working like a charm:
```bash
// Wire.setClock(400000)
```

Greetings from Germany,
DasKanu

**Comment by 1a2m3** [comment]
Thanks for your support.

I have defaulted I2C clock frequency to 100khz, and added clock frequency options to the "SpdReaderWriterSettings.h" file.
