### ISSUE TITLE
Possible to adapt the project to support DDR4 DIMM Slot/Sockets?

### ISSUE THREAD

**Issue by mparchm** [1a2m3/SPD-Reader-Writer#2]
It'd be great and make this project even better if there was the flexibility to quickly cycle modules/DIMMs through...e.g. to Fix up a set of modules rather quickly/for frequent/high volume use cases.

Could a PCB with a (or multiple) DIMM slot be created with exposed headers/2.54mm header pins for easy Arduino interfacing so you wire the Arduino up to the PCB and then it's as easy as loading DIMMs into the right slot (e.g. DDR3, DDR4, etc...) rather than spending time with wiring for each/every DIMM you wish to interact with?

I'd be interested in sponsoring the development of such a PCB if you would need to outsource it. In fact, I believe I know just the person and could get a quote from him/cover the costs associated to benefit this project. How might we get in touch to further collaborate on this? I have email, Discord, many other IMs, etc. Let me know!

Great work. Also, your specs on the forum; does X299SE2 refer to Sage II?

**Comment by 1a2m3** [comment]
_oh, and X299SE2 in my sig is **ROG Strix X299-E Gaming II**_
