### ISSUE TITLE
AMD FCH Smbus test

### ISSUE THREAD

**Issue by 1a2m3** [1a2m3/SPD-Reader-Writer#21]
AMD FCH Smbus test #<i></i>8

[20220520-amdtest8.zip](https://github.com/1a2m3/SPD-Reader-Writer/files/8747355/20220520-amdtest8.zip)

**Comment by OstrichPowers** [comment]
Data can be read but RSWP options are greyed out. Is this a function only supported with Arduino?

![spdrwgui_0162237](https://user-images.githubusercontent.com/108581584/177080921-403461f4-3f0a-4662-80f6-df2647796a96.png)

**Comment by 1a2m3** [comment]
Yes, RSWP operations require hardware Arduino-based programmer. However, you can still manually verify if RSWP is present by using "Check RSWP" option under EEPROM menu.
