### ISSUE TITLE
SPD-RW GUI crash when dialog Select Device openned

### ISSUE THREAD

**Issue by Sergey1Fox** [1a2m3/SPD-Reader-Writer#29]
Hardware: Dell XPS 9560, I7700HQ, chipset Kaby lake, HM175, DDR4

![2022-10-24_18-53-19](https://user-images.githubusercontent.com/116572262/197543844-e27f7b45-a3e0-4823-a4e5-cafc2a8f96e6.png)

**Comment by 1a2m3** [comment]
1. Do you have any serial port devices present?

2. Run CLI version as admin with the following parameters and show me the output:

- spdrwcli.exe /find
- spdrwcli.exe /find arduino
- spdrwcli.exe /find smbus

**Comment by Sergey1Fox** [comment]
1. Yes, two serial bluetooth ports (WIFI card Killer Wireless 1535)
2. First and second command were interrupted by CTRL+C after 1 minutes of waiting
 
![2022-10-26 23-26-17](https://user-images.githubusercontent.com/116572262/198108642-fde1edce-02ea-4606-84c3-a2fd30bd771b.png)

**Comment by 1a2m3** [comment]
Thanks. Issue identified and replicated with Bluetooth COM port present.

Replace the DLL file with this one and try both GUI and CLI versions again and report the results.

[20221026HF.zip](https://github.com/1a2m3/SPD-Reader-Writer/files/9874369/20221026HF.zip)

**Comment by Sergey1Fox** [comment]
Thank you. Now it works very well.

**Comment by 1a2m3** [comment]
Great. I'll post the fix as pre-release then until the full update is ready.
