### ISSUE TITLE
kindly please make 20230314 windows gui exe version 

### ISSUE THREAD

**Issue by arieslaptop** [1a2m3/SPD-Reader-Writer#33]
Dear sir , kindly please make exe file for windows . i am not aware how to compile it

**Comment by 1a2m3** [comment]
The [20230314](https://github.com/1a2m3/SPD-Reader-Writer/releases/tag/20230314) DLL is compatible with [20230205](https://github.com/1a2m3/SPD-Reader-Writer/releases/tag/20230205) GUI version. Just overwrite the file and wait for full release.
