### ISSUE TITLE
Paid purchase of equipment

### ISSUE THREAD

**Issue by steamsv** [1a2m3/SPD-Reader-Writer#42]
Hello, I am very interested in this project, but due to limited knowledge, some connection structures cannot be understood. Can I pay for the equipment that has been set up? I am a Chinese, located in Chinese Mainland, mailbox huweiguo4211@gmail.com You can use SF Express ，i can pay USDT TRC20

Or receive paid guidance

**Comment by 1a2m3** [comment]
Email sent, check your inbox.
